/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.5.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    flatDir {
        dirs("lib")
    }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.google.guava:guava:31.0.1-jre")

    implementation("javax.websocket:javax.websocket-api:1.1")
    implementation("org.eclipse.jetty.websocket:websocket-client:9.4.44.v20210927")
    implementation("org.springframework:spring-websocket:5.3.13")
    implementation("org.springframework:spring-messaging:5.3.13")

    implementation("be.fedict.commons-eid:commons-eid-client:0.6.6")
    implementation("be.fedict.commons-eid:commons-eid-consumer:0.6.6")
    implementation("be.fedict.commons-eid:commons-eid-jca:0.6.6")
    implementation("be.fedict.commons-eid:commons-eid-dialogs:0.6.6")

    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("ch.qos.logback:logback-core:1.2.3")

    implementation("org.slf4j:log4j-over-slf4j:1.7.25")
    implementation("org.slf4j:slf4j-api:1.7.25")

    implementation(group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version = "2.12.5")
    implementation(group = "com.fasterxml.jackson.core", name = "jackson-databind", version = "2.12.5")
    implementation(group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-smile", version = "2.12.5")
    implementation(group = "com.fasterxml.jackson.datatype", name="jackson-datatype-jsr310", version = "2.12.5")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    // Define the main class for the application.
    mainClass.set("io.icure.sts.client.AppKt")
}
